with-expecter: true
quiet: False
dir: "{{.PackageName}}/mocks"
outpkg: "mocks"
packages:
    github.com/regnull/ubikom/bc:
      interfaces:
        NameRegistryCaller:
        Blockchain:
    github.com/regnull/ubikom/protoutil:
      interfaces:
        DumpServiceClientFactory:
    github.com/regnull/ubikom/pb:
      interfaces:
        DMSDumpServiceClient: