// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ExternalSender is an autogenerated mock type for the ExternalSender type
type ExternalSender struct {
	mock.Mock
}

// Send provides a mock function with given fields: from, message
func (_m *ExternalSender) Send(from string, message string) (string, error) {
	ret := _m.Called(from, message)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(from, message)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(from, message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
