// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: ubikom_internal.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Timestamp when the key was registered.
	RegistrationTimestamp int64 `protobuf:"varint,1,opt,name=registration_timestamp,json=registrationTimestamp,proto3" json:"registration_timestamp,omitempty"`
	// Controls if the key is disabled. Once a key is disabled, it is dead forever.
	Disabled          bool   `protobuf:"varint,2,opt,name=disabled,proto3" json:"disabled,omitempty"`
	DisabledTimestamp int64  `protobuf:"varint,3,opt,name=disabled_timestamp,json=disabledTimestamp,proto3" json:"disabled_timestamp,omitempty"`
	DisabledBy        []byte `protobuf:"bytes,4,opt,name=disabled_by,json=disabledBy,proto3" json:"disabled_by,omitempty"`
	// Parent key (it can do everything this key can do).
	ParentKey [][]byte `protobuf:"bytes,5,rep,name=parent_key,json=parentKey,proto3" json:"parent_key,omitempty"`
}

func (x *KeyRecord) Reset() {
	*x = KeyRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_internal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyRecord) ProtoMessage() {}

func (x *KeyRecord) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_internal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyRecord.ProtoReflect.Descriptor instead.
func (*KeyRecord) Descriptor() ([]byte, []int) {
	return file_ubikom_internal_proto_rawDescGZIP(), []int{0}
}

func (x *KeyRecord) GetRegistrationTimestamp() int64 {
	if x != nil {
		return x.RegistrationTimestamp
	}
	return 0
}

func (x *KeyRecord) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *KeyRecord) GetDisabledTimestamp() int64 {
	if x != nil {
		return x.DisabledTimestamp
	}
	return 0
}

func (x *KeyRecord) GetDisabledBy() []byte {
	if x != nil {
		return x.DisabledBy
	}
	return nil
}

func (x *KeyRecord) GetParentKey() [][]byte {
	if x != nil {
		return x.ParentKey
	}
	return nil
}

type ExportKeyRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key                   []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	RegistrationTimestamp int64    `protobuf:"varint,2,opt,name=registration_timestamp,json=registrationTimestamp,proto3" json:"registration_timestamp,omitempty"`
	Disabled              bool     `protobuf:"varint,3,opt,name=disabled,proto3" json:"disabled,omitempty"`
	DisabledTimestamp     int64    `protobuf:"varint,4,opt,name=disabled_timestamp,json=disabledTimestamp,proto3" json:"disabled_timestamp,omitempty"`
	DisabledBy            []byte   `protobuf:"bytes,5,opt,name=disabled_by,json=disabledBy,proto3" json:"disabled_by,omitempty"`
	ParentKey             [][]byte `protobuf:"bytes,6,rep,name=parent_key,json=parentKey,proto3" json:"parent_key,omitempty"`
}

func (x *ExportKeyRecord) Reset() {
	*x = ExportKeyRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_internal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportKeyRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportKeyRecord) ProtoMessage() {}

func (x *ExportKeyRecord) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_internal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportKeyRecord.ProtoReflect.Descriptor instead.
func (*ExportKeyRecord) Descriptor() ([]byte, []int) {
	return file_ubikom_internal_proto_rawDescGZIP(), []int{1}
}

func (x *ExportKeyRecord) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ExportKeyRecord) GetRegistrationTimestamp() int64 {
	if x != nil {
		return x.RegistrationTimestamp
	}
	return 0
}

func (x *ExportKeyRecord) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *ExportKeyRecord) GetDisabledTimestamp() int64 {
	if x != nil {
		return x.DisabledTimestamp
	}
	return 0
}

func (x *ExportKeyRecord) GetDisabledBy() []byte {
	if x != nil {
		return x.DisabledBy
	}
	return nil
}

func (x *ExportKeyRecord) GetParentKey() [][]byte {
	if x != nil {
		return x.ParentKey
	}
	return nil
}

type ExportNameRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key  []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *ExportNameRecord) Reset() {
	*x = ExportNameRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_internal_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportNameRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportNameRecord) ProtoMessage() {}

func (x *ExportNameRecord) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_internal_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportNameRecord.ProtoReflect.Descriptor instead.
func (*ExportNameRecord) Descriptor() ([]byte, []int) {
	return file_ubikom_internal_proto_rawDescGZIP(), []int{2}
}

func (x *ExportNameRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExportNameRecord) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type ExportAddressRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Protocol Protocol `protobuf:"varint,2,opt,name=protocol,proto3,enum=Ubikom.Protocol" json:"protocol,omitempty"`
	Address  string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *ExportAddressRecord) Reset() {
	*x = ExportAddressRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_internal_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportAddressRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportAddressRecord) ProtoMessage() {}

func (x *ExportAddressRecord) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_internal_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportAddressRecord.ProtoReflect.Descriptor instead.
func (*ExportAddressRecord) Descriptor() ([]byte, []int) {
	return file_ubikom_internal_proto_rawDescGZIP(), []int{3}
}

func (x *ExportAddressRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExportAddressRecord) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PL_UNKNOWN
}

func (x *ExportAddressRecord) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type DBValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp uint64     `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload   *anypb.Any `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *DBValue) Reset() {
	*x = DBValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_internal_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBValue) ProtoMessage() {}

func (x *DBValue) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_internal_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBValue.ProtoReflect.Descriptor instead.
func (*DBValue) Descriptor() ([]byte, []int) {
	return file_ubikom_internal_proto_rawDescGZIP(), []int{4}
}

func (x *DBValue) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DBValue) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

type DBEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []*DBValue `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
}

func (x *DBEntry) Reset() {
	*x = DBEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_internal_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBEntry) ProtoMessage() {}

func (x *DBEntry) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_internal_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBEntry.ProtoReflect.Descriptor instead.
func (*DBEntry) Descriptor() ([]byte, []int) {
	return file_ubikom_internal_proto_rawDescGZIP(), []int{5}
}

func (x *DBEntry) GetValue() []*DBValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type ImapMailbox struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Attribute   []string `protobuf:"bytes,2,rep,name=attribute,proto3" json:"attribute,omitempty"`
	Id          string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"` // Unique ID for this mailbox. It never changes, even when mailbox is renamed.
	UidValidity uint32   `protobuf:"varint,4,opt,name=uid_validity,json=uidValidity,proto3" json:"uid_validity,omitempty"`
}

func (x *ImapMailbox) Reset() {
	*x = ImapMailbox{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_internal_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImapMailbox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImapMailbox) ProtoMessage() {}

func (x *ImapMailbox) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_internal_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImapMailbox.ProtoReflect.Descriptor instead.
func (*ImapMailbox) Descriptor() ([]byte, []int) {
	return file_ubikom_internal_proto_rawDescGZIP(), []int{6}
}

func (x *ImapMailbox) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImapMailbox) GetAttribute() []string {
	if x != nil {
		return x.Attribute
	}
	return nil
}

func (x *ImapMailbox) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImapMailbox) GetUidValidity() uint32 {
	if x != nil {
		return x.UidValidity
	}
	return 0
}

type ImapMailboxes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mailbox    []*ImapMailbox `protobuf:"bytes,1,rep,name=mailbox,proto3" json:"mailbox,omitempty"`
	Subscribed []string       `protobuf:"bytes,2,rep,name=subscribed,proto3" json:"subscribed,omitempty"`
}

func (x *ImapMailboxes) Reset() {
	*x = ImapMailboxes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_internal_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImapMailboxes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImapMailboxes) ProtoMessage() {}

func (x *ImapMailboxes) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_internal_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImapMailboxes.ProtoReflect.Descriptor instead.
func (*ImapMailboxes) Descriptor() ([]byte, []int) {
	return file_ubikom_internal_proto_rawDescGZIP(), []int{7}
}

func (x *ImapMailboxes) GetMailbox() []*ImapMailbox {
	if x != nil {
		return x.Mailbox
	}
	return nil
}

func (x *ImapMailboxes) GetSubscribed() []string {
	if x != nil {
		return x.Subscribed
	}
	return nil
}

var File_ubikom_internal_proto protoreflect.FileDescriptor

var file_ubikom_internal_proto_rawDesc = []byte{
	0x0a, 0x15, 0x75, 0x62, 0x69, 0x6b, 0x6f, 0x6d, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x55, 0x62, 0x69, 0x6b, 0x6f, 0x6d, 0x1a,
	0x0c, 0x75, 0x62, 0x69, 0x6b, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61,
	0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcd, 0x01, 0x0a, 0x09, 0x4b, 0x65, 0x79,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x35, 0x0a, 0x16, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x15, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1a, 0x0a,
	0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x2d, 0x0a, 0x12, 0x64, 0x69, 0x73,
	0x61, 0x62, 0x6c, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x61,
	0x62, 0x6c, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x64,
	0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x42, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x09, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x22, 0xe5, 0x01, 0x0a, 0x0f, 0x45, 0x78, 0x70,
	0x6f, 0x72, 0x74, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x35,
	0x0a, 0x16, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x15,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65,
	0x64, 0x12, 0x2d, 0x0a, 0x12, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x64,
	0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x42,
	0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x4b, 0x65, 0x79,
	0x22, 0x38, 0x0a, 0x10, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x71, 0x0a, 0x13, 0x45, 0x78,
	0x70, 0x6f, 0x72, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x55, 0x62, 0x69, 0x6b, 0x6f, 0x6d,
	0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x57, 0x0a,
	0x07, 0x44, 0x42, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x2e, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x30, 0x0a, 0x07, 0x44, 0x42, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x25, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x55, 0x62, 0x69, 0x6b, 0x6f, 0x6d, 0x2e, 0x44, 0x42, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x72, 0x0a, 0x0b, 0x49, 0x6d, 0x61, 0x70,
	0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09,
	0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x75, 0x69, 0x64,
	0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0b, 0x75, 0x69, 0x64, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x69, 0x74, 0x79, 0x22, 0x5e, 0x0a, 0x0d,
	0x49, 0x6d, 0x61, 0x70, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x65, 0x73, 0x12, 0x2d, 0x0a,
	0x07, 0x6d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x55, 0x62, 0x69, 0x6b, 0x6f, 0x6d, 0x2e, 0x49, 0x6d, 0x61, 0x70, 0x4d, 0x61, 0x69, 0x6c,
	0x62, 0x6f, 0x78, 0x52, 0x07, 0x6d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x12, 0x1e, 0x0a, 0x0a,
	0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0a, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x64, 0x42, 0x07, 0x5a, 0x05,
	0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ubikom_internal_proto_rawDescOnce sync.Once
	file_ubikom_internal_proto_rawDescData = file_ubikom_internal_proto_rawDesc
)

func file_ubikom_internal_proto_rawDescGZIP() []byte {
	file_ubikom_internal_proto_rawDescOnce.Do(func() {
		file_ubikom_internal_proto_rawDescData = protoimpl.X.CompressGZIP(file_ubikom_internal_proto_rawDescData)
	})
	return file_ubikom_internal_proto_rawDescData
}

var file_ubikom_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_ubikom_internal_proto_goTypes = []interface{}{
	(*KeyRecord)(nil),           // 0: Ubikom.KeyRecord
	(*ExportKeyRecord)(nil),     // 1: Ubikom.ExportKeyRecord
	(*ExportNameRecord)(nil),    // 2: Ubikom.ExportNameRecord
	(*ExportAddressRecord)(nil), // 3: Ubikom.ExportAddressRecord
	(*DBValue)(nil),             // 4: Ubikom.DBValue
	(*DBEntry)(nil),             // 5: Ubikom.DBEntry
	(*ImapMailbox)(nil),         // 6: Ubikom.ImapMailbox
	(*ImapMailboxes)(nil),       // 7: Ubikom.ImapMailboxes
	(Protocol)(0),               // 8: Ubikom.Protocol
	(*anypb.Any)(nil),           // 9: google.protobuf.Any
}
var file_ubikom_internal_proto_depIdxs = []int32{
	8, // 0: Ubikom.ExportAddressRecord.protocol:type_name -> Ubikom.Protocol
	9, // 1: Ubikom.DBValue.payload:type_name -> google.protobuf.Any
	4, // 2: Ubikom.DBEntry.value:type_name -> Ubikom.DBValue
	6, // 3: Ubikom.ImapMailboxes.mailbox:type_name -> Ubikom.ImapMailbox
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ubikom_internal_proto_init() }
func file_ubikom_internal_proto_init() {
	if File_ubikom_internal_proto != nil {
		return
	}
	file_ubikom_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ubikom_internal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ubikom_internal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportKeyRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ubikom_internal_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportNameRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ubikom_internal_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportAddressRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ubikom_internal_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ubikom_internal_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ubikom_internal_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImapMailbox); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ubikom_internal_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImapMailboxes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ubikom_internal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ubikom_internal_proto_goTypes,
		DependencyIndexes: file_ubikom_internal_proto_depIdxs,
		MessageInfos:      file_ubikom_internal_proto_msgTypes,
	}.Build()
	File_ubikom_internal_proto = out.File
	file_ubikom_internal_proto_rawDesc = nil
	file_ubikom_internal_proto_goTypes = nil
	file_ubikom_internal_proto_depIdxs = nil
}
