// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: ubikom.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Protocol int32

const (
	Protocol_PL_UNKNOWN Protocol = 0
	Protocol_PL_DMS     Protocol = 1
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "PL_UNKNOWN",
		1: "PL_DMS",
	}
	Protocol_value = map[string]int32{
		"PL_UNKNOWN": 0,
		"PL_DMS":     1,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_ubikom_proto_enumTypes[0].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_ubikom_proto_enumTypes[0]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_ubikom_proto_rawDescGZIP(), []int{0}
}

type EllipticCurve int32

const (
	EllipticCurve_EC_UNKNOWN   EllipticCurve = 0
	EllipticCurve_EC_SECP256K1 EllipticCurve = 1
	EllipticCurve_EC_P_256     EllipticCurve = 2
	EllipticCurve_EC_P_384     EllipticCurve = 3
	EllipticCurve_EC_P_521     EllipticCurve = 4
)

// Enum value maps for EllipticCurve.
var (
	EllipticCurve_name = map[int32]string{
		0: "EC_UNKNOWN",
		1: "EC_SECP256K1",
		2: "EC_P_256",
		3: "EC_P_384",
		4: "EC_P_521",
	}
	EllipticCurve_value = map[string]int32{
		"EC_UNKNOWN":   0,
		"EC_SECP256K1": 1,
		"EC_P_256":     2,
		"EC_P_384":     3,
		"EC_P_521":     4,
	}
)

func (x EllipticCurve) Enum() *EllipticCurve {
	p := new(EllipticCurve)
	*p = x
	return p
}

func (x EllipticCurve) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EllipticCurve) Descriptor() protoreflect.EnumDescriptor {
	return file_ubikom_proto_enumTypes[1].Descriptor()
}

func (EllipticCurve) Type() protoreflect.EnumType {
	return &file_ubikom_proto_enumTypes[1]
}

func (x EllipticCurve) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EllipticCurve.Descriptor instead.
func (EllipticCurve) EnumDescriptor() ([]byte, []int) {
	return file_ubikom_proto_rawDescGZIP(), []int{1}
}

type ContentWithPOW struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content []byte `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Pow     []byte `protobuf:"bytes,2,opt,name=pow,proto3" json:"pow,omitempty"`
}

func (x *ContentWithPOW) Reset() {
	*x = ContentWithPOW{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContentWithPOW) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentWithPOW) ProtoMessage() {}

func (x *ContentWithPOW) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentWithPOW.ProtoReflect.Descriptor instead.
func (*ContentWithPOW) Descriptor() ([]byte, []int) {
	return file_ubikom_proto_rawDescGZIP(), []int{0}
}

func (x *ContentWithPOW) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ContentWithPOW) GetPow() []byte {
	if x != nil {
		return x.Pow
	}
	return nil
}

type Signature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	R []byte `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
	S []byte `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
}

func (x *Signature) Reset() {
	*x = Signature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_ubikom_proto_rawDescGZIP(), []int{1}
}

func (x *Signature) GetR() []byte {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *Signature) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

type Signed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content   []byte     `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Signature *Signature `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Key       []byte     `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *Signed) Reset() {
	*x = Signed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Signed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signed) ProtoMessage() {}

func (x *Signed) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signed.ProtoReflect.Descriptor instead.
func (*Signed) Descriptor() ([]byte, []int) {
	return file_ubikom_proto_rawDescGZIP(), []int{2}
}

func (x *Signed) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Signed) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Signed) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type SignedWithPow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content   []byte     `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Signature *Signature `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Key       []byte     `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"` // Public key used to sign the request.
	Pow       []byte     `protobuf:"bytes,4,opt,name=pow,proto3" json:"pow,omitempty"`
}

func (x *SignedWithPow) Reset() {
	*x = SignedWithPow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignedWithPow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedWithPow) ProtoMessage() {}

func (x *SignedWithPow) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedWithPow.ProtoReflect.Descriptor instead.
func (*SignedWithPow) Descriptor() ([]byte, []int) {
	return file_ubikom_proto_rawDescGZIP(), []int{3}
}

func (x *SignedWithPow) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *SignedWithPow) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignedWithPow) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SignedWithPow) GetPow() []byte {
	if x != nil {
		return x.Pow
	}
	return nil
}

type CryptoContext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EllipticCurve EllipticCurve `protobuf:"varint,1,opt,name=elliptic_curve,json=ellipticCurve,proto3,enum=Ubikom.EllipticCurve" json:"elliptic_curve,omitempty"`
	EcdhVersion   int32         `protobuf:"varint,2,opt,name=ecdh_version,json=ecdhVersion,proto3" json:"ecdh_version,omitempty"`
	EcdsaVersion  int32         `protobuf:"varint,3,opt,name=ecdsa_version,json=ecdsaVersion,proto3" json:"ecdsa_version,omitempty"`
}

func (x *CryptoContext) Reset() {
	*x = CryptoContext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CryptoContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoContext) ProtoMessage() {}

func (x *CryptoContext) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoContext.ProtoReflect.Descriptor instead.
func (*CryptoContext) Descriptor() ([]byte, []int) {
	return file_ubikom_proto_rawDescGZIP(), []int{4}
}

func (x *CryptoContext) GetEllipticCurve() EllipticCurve {
	if x != nil {
		return x.EllipticCurve
	}
	return EllipticCurve_EC_UNKNOWN
}

func (x *CryptoContext) GetEcdhVersion() int32 {
	if x != nil {
		return x.EcdhVersion
	}
	return 0
}

func (x *CryptoContext) GetEcdsaVersion() int32 {
	if x != nil {
		return x.EcdsaVersion
	}
	return 0
}

type LookupKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *LookupKeyRequest) Reset() {
	*x = LookupKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupKeyRequest) ProtoMessage() {}

func (x *LookupKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupKeyRequest.ProtoReflect.Descriptor instead.
func (*LookupKeyRequest) Descriptor() ([]byte, []int) {
	return file_ubikom_proto_rawDescGZIP(), []int{5}
}

func (x *LookupKeyRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type LookupKeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RegistrationTimestamp int64    `protobuf:"varint,1,opt,name=registration_timestamp,json=registrationTimestamp,proto3" json:"registration_timestamp,omitempty"`
	Disabled              bool     `protobuf:"varint,2,opt,name=disabled,proto3" json:"disabled,omitempty"`
	DisabledTimestamp     int64    `protobuf:"varint,3,opt,name=disabled_timestamp,json=disabledTimestamp,proto3" json:"disabled_timestamp,omitempty"`
	DisabledBy            []byte   `protobuf:"bytes,4,opt,name=disabled_by,json=disabledBy,proto3" json:"disabled_by,omitempty"`
	ParentKey             [][]byte `protobuf:"bytes,5,rep,name=parent_key,json=parentKey,proto3" json:"parent_key,omitempty"`
}

func (x *LookupKeyResponse) Reset() {
	*x = LookupKeyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupKeyResponse) ProtoMessage() {}

func (x *LookupKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupKeyResponse.ProtoReflect.Descriptor instead.
func (*LookupKeyResponse) Descriptor() ([]byte, []int) {
	return file_ubikom_proto_rawDescGZIP(), []int{6}
}

func (x *LookupKeyResponse) GetRegistrationTimestamp() int64 {
	if x != nil {
		return x.RegistrationTimestamp
	}
	return 0
}

func (x *LookupKeyResponse) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *LookupKeyResponse) GetDisabledTimestamp() int64 {
	if x != nil {
		return x.DisabledTimestamp
	}
	return 0
}

func (x *LookupKeyResponse) GetDisabledBy() []byte {
	if x != nil {
		return x.DisabledBy
	}
	return nil
}

func (x *LookupKeyResponse) GetParentKey() [][]byte {
	if x != nil {
		return x.ParentKey
	}
	return nil
}

type LookupNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *LookupNameRequest) Reset() {
	*x = LookupNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupNameRequest) ProtoMessage() {}

func (x *LookupNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupNameRequest.ProtoReflect.Descriptor instead.
func (*LookupNameRequest) Descriptor() ([]byte, []int) {
	return file_ubikom_proto_rawDescGZIP(), []int{7}
}

func (x *LookupNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LookupNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *LookupNameResponse) Reset() {
	*x = LookupNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupNameResponse) ProtoMessage() {}

func (x *LookupNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupNameResponse.ProtoReflect.Descriptor instead.
func (*LookupNameResponse) Descriptor() ([]byte, []int) {
	return file_ubikom_proto_rawDescGZIP(), []int{8}
}

func (x *LookupNameResponse) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type LookupAddressRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Protocol Protocol `protobuf:"varint,2,opt,name=protocol,proto3,enum=Ubikom.Protocol" json:"protocol,omitempty"`
}

func (x *LookupAddressRequest) Reset() {
	*x = LookupAddressRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupAddressRequest) ProtoMessage() {}

func (x *LookupAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupAddressRequest.ProtoReflect.Descriptor instead.
func (*LookupAddressRequest) Descriptor() ([]byte, []int) {
	return file_ubikom_proto_rawDescGZIP(), []int{9}
}

func (x *LookupAddressRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LookupAddressRequest) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PL_UNKNOWN
}

type LookupAddressResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *LookupAddressResponse) Reset() {
	*x = LookupAddressResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupAddressResponse) ProtoMessage() {}

func (x *LookupAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupAddressResponse.ProtoReflect.Descriptor instead.
func (*LookupAddressResponse) Descriptor() ([]byte, []int) {
	return file_ubikom_proto_rawDescGZIP(), []int{10}
}

func (x *LookupAddressResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LookupAddressResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type DMSMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Sender's address.
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// Receiver's address.
	Receiver      string         `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Content       []byte         `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Signature     *Signature     `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	CryptoContext *CryptoContext `protobuf:"bytes,5,opt,name=crypto_context,json=cryptoContext,proto3" json:"crypto_context,omitempty"`
}

func (x *DMSMessage) Reset() {
	*x = DMSMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DMSMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DMSMessage) ProtoMessage() {}

func (x *DMSMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DMSMessage.ProtoReflect.Descriptor instead.
func (*DMSMessage) Descriptor() ([]byte, []int) {
	return file_ubikom_proto_rawDescGZIP(), []int{11}
}

func (x *DMSMessage) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *DMSMessage) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *DMSMessage) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *DMSMessage) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *DMSMessage) GetCryptoContext() *CryptoContext {
	if x != nil {
		return x.CryptoContext
	}
	return nil
}

type SendRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message *DMSMessage `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_ubikom_proto_rawDescGZIP(), []int{12}
}

func (x *SendRequest) GetMessage() *DMSMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type SendResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_ubikom_proto_rawDescGZIP(), []int{13}
}

type ReceiveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdentityProof *Signed        `protobuf:"bytes,1,opt,name=identity_proof,json=identityProof,proto3" json:"identity_proof,omitempty"`
	CrytoContext  *CryptoContext `protobuf:"bytes,2,opt,name=cryto_context,json=crytoContext,proto3" json:"cryto_context,omitempty"`
}

func (x *ReceiveRequest) Reset() {
	*x = ReceiveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveRequest) ProtoMessage() {}

func (x *ReceiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveRequest.ProtoReflect.Descriptor instead.
func (*ReceiveRequest) Descriptor() ([]byte, []int) {
	return file_ubikom_proto_rawDescGZIP(), []int{14}
}

func (x *ReceiveRequest) GetIdentityProof() *Signed {
	if x != nil {
		return x.IdentityProof
	}
	return nil
}

func (x *ReceiveRequest) GetCrytoContext() *CryptoContext {
	if x != nil {
		return x.CrytoContext
	}
	return nil
}

type ReceiveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message *DMSMessage `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ReceiveResponse) Reset() {
	*x = ReceiveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveResponse) ProtoMessage() {}

func (x *ReceiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveResponse.ProtoReflect.Descriptor instead.
func (*ReceiveResponse) Descriptor() ([]byte, []int) {
	return file_ubikom_proto_rawDescGZIP(), []int{15}
}

func (x *ReceiveResponse) GetMessage() *DMSMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_ubikom_proto protoreflect.FileDescriptor

var file_ubikom_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x75, 0x62, 0x69, 0x6b, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x55, 0x62, 0x69, 0x6b, 0x6f, 0x6d, 0x22, 0x3c, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x57, 0x69, 0x74, 0x68, 0x50, 0x4f, 0x57, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x03, 0x70, 0x6f, 0x77, 0x22, 0x27, 0x0a, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x12, 0x0c, 0x0a, 0x01, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x72, 0x12,
	0x0c, 0x0a, 0x01, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x73, 0x22, 0x65, 0x0a,
	0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x12, 0x2f, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x55, 0x62, 0x69, 0x6b, 0x6f, 0x6d, 0x2e, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x22, 0x7e, 0x0a, 0x0d, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x57, 0x69,
	0x74, 0x68, 0x50, 0x6f, 0x77, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12,
	0x2f, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x55, 0x62, 0x69, 0x6b, 0x6f, 0x6d, 0x2e, 0x53, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f, 0x77, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x03, 0x70, 0x6f, 0x77, 0x22, 0x95, 0x01, 0x0a, 0x0d, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x3c, 0x0a, 0x0e, 0x65, 0x6c, 0x6c, 0x69, 0x70, 0x74,
	0x69, 0x63, 0x5f, 0x63, 0x75, 0x72, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15,
	0x2e, 0x55, 0x62, 0x69, 0x6b, 0x6f, 0x6d, 0x2e, 0x45, 0x6c, 0x6c, 0x69, 0x70, 0x74, 0x69, 0x63,
	0x43, 0x75, 0x72, 0x76, 0x65, 0x52, 0x0d, 0x65, 0x6c, 0x6c, 0x69, 0x70, 0x74, 0x69, 0x63, 0x43,
	0x75, 0x72, 0x76, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x65, 0x63, 0x64, 0x68, 0x5f, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x65, 0x63, 0x64, 0x68,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x63, 0x64, 0x73, 0x61,
	0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c,
	0x65, 0x63, 0x64, 0x73, 0x61, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x24, 0x0a, 0x10,
	0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x22, 0xd5, 0x01, 0x0a, 0x11, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x4b, 0x65, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x16, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x15, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12,
	0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x2d, 0x0a, 0x12, 0x64,
	0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x69,
	0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0a, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x42, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0c, 0x52,
	0x09, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x22, 0x27, 0x0a, 0x11, 0x4c, 0x6f,
	0x6f, 0x6b, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x26, 0x0a, 0x12, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x4e, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x58, 0x0a, 0x14, 0x4c,
	0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x55, 0x62, 0x69, 0x6b,
	0x6f, 0x6d, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x52, 0x08, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0x4b, 0x0a, 0x15, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x22, 0xc9, 0x01, 0x0a, 0x0a, 0x44, 0x4d, 0x53, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12,
	0x2f, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x55, 0x62, 0x69, 0x6b, 0x6f, 0x6d, 0x2e, 0x53, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x12, 0x3c, 0x0a, 0x0e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x78, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x55, 0x62, 0x69, 0x6b, 0x6f,
	0x6d, 0x2e, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52,
	0x0d, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x22, 0x3b,
	0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x55, 0x62, 0x69, 0x6b, 0x6f, 0x6d, 0x2e, 0x44, 0x4d, 0x53, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x0e, 0x0a, 0x0c, 0x53,
	0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x83, 0x01, 0x0a, 0x0e,
	0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35,
	0x0a, 0x0e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x70, 0x72, 0x6f, 0x6f, 0x66,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x55, 0x62, 0x69, 0x6b, 0x6f, 0x6d, 0x2e,
	0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x52, 0x0d, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x3a, 0x0a, 0x0d, 0x63, 0x72, 0x79, 0x74, 0x6f, 0x5f, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x55,
	0x62, 0x69, 0x6b, 0x6f, 0x6d, 0x2e, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x78, 0x74, 0x52, 0x0c, 0x63, 0x72, 0x79, 0x74, 0x6f, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78,
	0x74, 0x22, 0x3f, 0x0a, 0x0f, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x55, 0x62, 0x69, 0x6b, 0x6f, 0x6d, 0x2e, 0x44,
	0x4d, 0x53, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2a, 0x26, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x0e,
	0x0a, 0x0a, 0x50, 0x4c, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0a,
	0x0a, 0x06, 0x50, 0x4c, 0x5f, 0x44, 0x4d, 0x53, 0x10, 0x01, 0x2a, 0x5b, 0x0a, 0x0d, 0x45, 0x6c,
	0x6c, 0x69, 0x70, 0x74, 0x69, 0x63, 0x43, 0x75, 0x72, 0x76, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x45,
	0x43, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x45,
	0x43, 0x5f, 0x53, 0x45, 0x43, 0x50, 0x32, 0x35, 0x36, 0x4b, 0x31, 0x10, 0x01, 0x12, 0x0c, 0x0a,
	0x08, 0x45, 0x43, 0x5f, 0x50, 0x5f, 0x32, 0x35, 0x36, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x45,
	0x43, 0x5f, 0x50, 0x5f, 0x33, 0x38, 0x34, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x45, 0x43, 0x5f,
	0x50, 0x5f, 0x35, 0x32, 0x31, 0x10, 0x04, 0x32, 0xe4, 0x01, 0x0a, 0x0d, 0x4c, 0x6f, 0x6f, 0x6b,
	0x75, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x09, 0x4c, 0x6f, 0x6f,
	0x6b, 0x75, 0x70, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x2e, 0x55, 0x62, 0x69, 0x6b, 0x6f, 0x6d, 0x2e,
	0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x55, 0x62, 0x69, 0x6b, 0x6f, 0x6d, 0x2e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70,
	0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x0a, 0x4c,
	0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x2e, 0x55, 0x62, 0x69, 0x6b,
	0x6f, 0x6d, 0x2e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x55, 0x62, 0x69, 0x6b, 0x6f, 0x6d, 0x2e, 0x4c, 0x6f,
	0x6f, 0x6b, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x4c, 0x0a, 0x0d, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x1c, 0x2e, 0x55, 0x62, 0x69, 0x6b, 0x6f, 0x6d, 0x2e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75,
	0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x55, 0x62, 0x69, 0x6b, 0x6f, 0x6d, 0x2e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x7f,
	0x0a, 0x0e, 0x44, 0x4d, 0x53, 0x44, 0x75, 0x6d, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x31, 0x0a, 0x04, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x13, 0x2e, 0x55, 0x62, 0x69, 0x6b, 0x6f,
	0x6d, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e,
	0x55, 0x62, 0x69, 0x6b, 0x6f, 0x6d, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x07, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x12, 0x16,
	0x2e, 0x55, 0x62, 0x69, 0x6b, 0x6f, 0x6d, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x55, 0x62, 0x69, 0x6b, 0x6f, 0x6d, 0x2e,
	0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ubikom_proto_rawDescOnce sync.Once
	file_ubikom_proto_rawDescData = file_ubikom_proto_rawDesc
)

func file_ubikom_proto_rawDescGZIP() []byte {
	file_ubikom_proto_rawDescOnce.Do(func() {
		file_ubikom_proto_rawDescData = protoimpl.X.CompressGZIP(file_ubikom_proto_rawDescData)
	})
	return file_ubikom_proto_rawDescData
}

var file_ubikom_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ubikom_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_ubikom_proto_goTypes = []interface{}{
	(Protocol)(0),                 // 0: Ubikom.Protocol
	(EllipticCurve)(0),            // 1: Ubikom.EllipticCurve
	(*ContentWithPOW)(nil),        // 2: Ubikom.ContentWithPOW
	(*Signature)(nil),             // 3: Ubikom.Signature
	(*Signed)(nil),                // 4: Ubikom.Signed
	(*SignedWithPow)(nil),         // 5: Ubikom.SignedWithPow
	(*CryptoContext)(nil),         // 6: Ubikom.CryptoContext
	(*LookupKeyRequest)(nil),      // 7: Ubikom.LookupKeyRequest
	(*LookupKeyResponse)(nil),     // 8: Ubikom.LookupKeyResponse
	(*LookupNameRequest)(nil),     // 9: Ubikom.LookupNameRequest
	(*LookupNameResponse)(nil),    // 10: Ubikom.LookupNameResponse
	(*LookupAddressRequest)(nil),  // 11: Ubikom.LookupAddressRequest
	(*LookupAddressResponse)(nil), // 12: Ubikom.LookupAddressResponse
	(*DMSMessage)(nil),            // 13: Ubikom.DMSMessage
	(*SendRequest)(nil),           // 14: Ubikom.SendRequest
	(*SendResponse)(nil),          // 15: Ubikom.SendResponse
	(*ReceiveRequest)(nil),        // 16: Ubikom.ReceiveRequest
	(*ReceiveResponse)(nil),       // 17: Ubikom.ReceiveResponse
}
var file_ubikom_proto_depIdxs = []int32{
	3,  // 0: Ubikom.Signed.signature:type_name -> Ubikom.Signature
	3,  // 1: Ubikom.SignedWithPow.signature:type_name -> Ubikom.Signature
	1,  // 2: Ubikom.CryptoContext.elliptic_curve:type_name -> Ubikom.EllipticCurve
	0,  // 3: Ubikom.LookupAddressRequest.protocol:type_name -> Ubikom.Protocol
	3,  // 4: Ubikom.DMSMessage.signature:type_name -> Ubikom.Signature
	6,  // 5: Ubikom.DMSMessage.crypto_context:type_name -> Ubikom.CryptoContext
	13, // 6: Ubikom.SendRequest.message:type_name -> Ubikom.DMSMessage
	4,  // 7: Ubikom.ReceiveRequest.identity_proof:type_name -> Ubikom.Signed
	6,  // 8: Ubikom.ReceiveRequest.cryto_context:type_name -> Ubikom.CryptoContext
	13, // 9: Ubikom.ReceiveResponse.message:type_name -> Ubikom.DMSMessage
	7,  // 10: Ubikom.LookupService.LookupKey:input_type -> Ubikom.LookupKeyRequest
	9,  // 11: Ubikom.LookupService.LookupName:input_type -> Ubikom.LookupNameRequest
	11, // 12: Ubikom.LookupService.LookupAddress:input_type -> Ubikom.LookupAddressRequest
	14, // 13: Ubikom.DMSDumpService.Send:input_type -> Ubikom.SendRequest
	16, // 14: Ubikom.DMSDumpService.Receive:input_type -> Ubikom.ReceiveRequest
	8,  // 15: Ubikom.LookupService.LookupKey:output_type -> Ubikom.LookupKeyResponse
	10, // 16: Ubikom.LookupService.LookupName:output_type -> Ubikom.LookupNameResponse
	12, // 17: Ubikom.LookupService.LookupAddress:output_type -> Ubikom.LookupAddressResponse
	15, // 18: Ubikom.DMSDumpService.Send:output_type -> Ubikom.SendResponse
	17, // 19: Ubikom.DMSDumpService.Receive:output_type -> Ubikom.ReceiveResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_ubikom_proto_init() }
func file_ubikom_proto_init() {
	if File_ubikom_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ubikom_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContentWithPOW); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ubikom_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Signature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ubikom_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Signed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ubikom_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignedWithPow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ubikom_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CryptoContext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ubikom_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ubikom_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupKeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ubikom_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ubikom_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ubikom_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupAddressRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ubikom_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupAddressResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ubikom_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DMSMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ubikom_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ubikom_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ubikom_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ubikom_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ubikom_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_ubikom_proto_goTypes,
		DependencyIndexes: file_ubikom_proto_depIdxs,
		EnumInfos:         file_ubikom_proto_enumTypes,
		MessageInfos:      file_ubikom_proto_msgTypes,
	}.Build()
	File_ubikom_proto = out.File
	file_ubikom_proto_rawDesc = nil
	file_ubikom_proto_goTypes = nil
	file_ubikom_proto_depIdxs = nil
}
