// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.9
// source: ubikom_internal.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_ET_NONE EventType = 0
	// Registration events.
	EventType_ET_KEY_REGISTRATION     EventType = 1
	EventType_ET_NAME_REGISTRATION    EventType = 2
	EventType_ET_ADDRESS_REGISTRATION EventType = 3
	// Proxy events - POP.
	EventType_ET_PROXY_POP_LOGIN EventType = 1001
	// Proxy events - IMAP.
	EventType_ET_PROXY_IMAP_LOGIN EventType = 1101
	// Proxy events - SMTP.
	EventType_ET_PROXY_SMTP_LOGIN        EventType = 1201
	EventType_ET_PROXY_SMTP_MESSAGE_SENT EventType = 1202
	// Proxy events - Web Mail.
	EventType_ET_PROXY_WEBMAIL_LOGIN        EventType = 1301
	EventType_ET_PROXY_WEBMAIL_MESSAGE_SENT EventType = 1302
	// Gateway events.
	EventType_ET_GATEWAY_UBIKOM_MESSAGE_RECEIVED EventType = 2001
	EventType_ET_GATEWAY_EMAIL_MESSAGE_RECEIVED  EventType = 2002
	EventType_ET_GATEWAY_UBIKOM_MESSAGE_SENT     EventType = 2003
	EventType_ET_GATEWAY_EMAIL_MESSAGE_SENT      EventType = 2004
	// Web events.
	EventType_ET_PAGE_SERVED EventType = 3001
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:    "ET_NONE",
		1:    "ET_KEY_REGISTRATION",
		2:    "ET_NAME_REGISTRATION",
		3:    "ET_ADDRESS_REGISTRATION",
		1001: "ET_PROXY_POP_LOGIN",
		1101: "ET_PROXY_IMAP_LOGIN",
		1201: "ET_PROXY_SMTP_LOGIN",
		1202: "ET_PROXY_SMTP_MESSAGE_SENT",
		1301: "ET_PROXY_WEBMAIL_LOGIN",
		1302: "ET_PROXY_WEBMAIL_MESSAGE_SENT",
		2001: "ET_GATEWAY_UBIKOM_MESSAGE_RECEIVED",
		2002: "ET_GATEWAY_EMAIL_MESSAGE_RECEIVED",
		2003: "ET_GATEWAY_UBIKOM_MESSAGE_SENT",
		2004: "ET_GATEWAY_EMAIL_MESSAGE_SENT",
		3001: "ET_PAGE_SERVED",
	}
	EventType_value = map[string]int32{
		"ET_NONE":                            0,
		"ET_KEY_REGISTRATION":                1,
		"ET_NAME_REGISTRATION":               2,
		"ET_ADDRESS_REGISTRATION":            3,
		"ET_PROXY_POP_LOGIN":                 1001,
		"ET_PROXY_IMAP_LOGIN":                1101,
		"ET_PROXY_SMTP_LOGIN":                1201,
		"ET_PROXY_SMTP_MESSAGE_SENT":         1202,
		"ET_PROXY_WEBMAIL_LOGIN":             1301,
		"ET_PROXY_WEBMAIL_MESSAGE_SENT":      1302,
		"ET_GATEWAY_UBIKOM_MESSAGE_RECEIVED": 2001,
		"ET_GATEWAY_EMAIL_MESSAGE_RECEIVED":  2002,
		"ET_GATEWAY_UBIKOM_MESSAGE_SENT":     2003,
		"ET_GATEWAY_EMAIL_MESSAGE_SENT":      2004,
		"ET_PAGE_SERVED":                     3001,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_ubikom_internal_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_ubikom_internal_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_ubikom_internal_proto_rawDescGZIP(), []int{0}
}

type KeyRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Timestamp when the key was registered.
	RegistrationTimestamp int64 `protobuf:"varint,1,opt,name=registration_timestamp,json=registrationTimestamp,proto3" json:"registration_timestamp,omitempty"`
	// Controls if the key is disabled. Once a key is disabled, it is dead forever.
	Disabled          bool   `protobuf:"varint,2,opt,name=disabled,proto3" json:"disabled,omitempty"`
	DisabledTimestamp int64  `protobuf:"varint,3,opt,name=disabled_timestamp,json=disabledTimestamp,proto3" json:"disabled_timestamp,omitempty"`
	DisabledBy        []byte `protobuf:"bytes,4,opt,name=disabled_by,json=disabledBy,proto3" json:"disabled_by,omitempty"`
	// Parent key (it can do everything this key can do).
	ParentKey [][]byte `protobuf:"bytes,5,rep,name=parent_key,json=parentKey,proto3" json:"parent_key,omitempty"`
}

func (x *KeyRecord) Reset() {
	*x = KeyRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_internal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyRecord) ProtoMessage() {}

func (x *KeyRecord) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_internal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyRecord.ProtoReflect.Descriptor instead.
func (*KeyRecord) Descriptor() ([]byte, []int) {
	return file_ubikom_internal_proto_rawDescGZIP(), []int{0}
}

func (x *KeyRecord) GetRegistrationTimestamp() int64 {
	if x != nil {
		return x.RegistrationTimestamp
	}
	return 0
}

func (x *KeyRecord) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *KeyRecord) GetDisabledTimestamp() int64 {
	if x != nil {
		return x.DisabledTimestamp
	}
	return 0
}

func (x *KeyRecord) GetDisabledBy() []byte {
	if x != nil {
		return x.DisabledBy
	}
	return nil
}

func (x *KeyRecord) GetParentKey() [][]byte {
	if x != nil {
		return x.ParentKey
	}
	return nil
}

type ExportKeyRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key                   []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	RegistrationTimestamp int64    `protobuf:"varint,2,opt,name=registration_timestamp,json=registrationTimestamp,proto3" json:"registration_timestamp,omitempty"`
	Disabled              bool     `protobuf:"varint,3,opt,name=disabled,proto3" json:"disabled,omitempty"`
	DisabledTimestamp     int64    `protobuf:"varint,4,opt,name=disabled_timestamp,json=disabledTimestamp,proto3" json:"disabled_timestamp,omitempty"`
	DisabledBy            []byte   `protobuf:"bytes,5,opt,name=disabled_by,json=disabledBy,proto3" json:"disabled_by,omitempty"`
	ParentKey             [][]byte `protobuf:"bytes,6,rep,name=parent_key,json=parentKey,proto3" json:"parent_key,omitempty"`
}

func (x *ExportKeyRecord) Reset() {
	*x = ExportKeyRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_internal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportKeyRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportKeyRecord) ProtoMessage() {}

func (x *ExportKeyRecord) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_internal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportKeyRecord.ProtoReflect.Descriptor instead.
func (*ExportKeyRecord) Descriptor() ([]byte, []int) {
	return file_ubikom_internal_proto_rawDescGZIP(), []int{1}
}

func (x *ExportKeyRecord) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ExportKeyRecord) GetRegistrationTimestamp() int64 {
	if x != nil {
		return x.RegistrationTimestamp
	}
	return 0
}

func (x *ExportKeyRecord) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *ExportKeyRecord) GetDisabledTimestamp() int64 {
	if x != nil {
		return x.DisabledTimestamp
	}
	return 0
}

func (x *ExportKeyRecord) GetDisabledBy() []byte {
	if x != nil {
		return x.DisabledBy
	}
	return nil
}

func (x *ExportKeyRecord) GetParentKey() [][]byte {
	if x != nil {
		return x.ParentKey
	}
	return nil
}

type ExportNameRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key  []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *ExportNameRecord) Reset() {
	*x = ExportNameRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_internal_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportNameRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportNameRecord) ProtoMessage() {}

func (x *ExportNameRecord) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_internal_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportNameRecord.ProtoReflect.Descriptor instead.
func (*ExportNameRecord) Descriptor() ([]byte, []int) {
	return file_ubikom_internal_proto_rawDescGZIP(), []int{2}
}

func (x *ExportNameRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExportNameRecord) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type ExportAddressRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Protocol Protocol `protobuf:"varint,2,opt,name=protocol,proto3,enum=Ubikom.Protocol" json:"protocol,omitempty"`
	Address  string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *ExportAddressRecord) Reset() {
	*x = ExportAddressRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_internal_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportAddressRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportAddressRecord) ProtoMessage() {}

func (x *ExportAddressRecord) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_internal_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportAddressRecord.ProtoReflect.Descriptor instead.
func (*ExportAddressRecord) Descriptor() ([]byte, []int) {
	return file_ubikom_internal_proto_rawDescGZIP(), []int{3}
}

func (x *ExportAddressRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExportAddressRecord) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PL_UNKNOWN
}

func (x *ExportAddressRecord) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type DBValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp uint64     `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload   *anypb.Any `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *DBValue) Reset() {
	*x = DBValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_internal_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBValue) ProtoMessage() {}

func (x *DBValue) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_internal_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBValue.ProtoReflect.Descriptor instead.
func (*DBValue) Descriptor() ([]byte, []int) {
	return file_ubikom_internal_proto_rawDescGZIP(), []int{4}
}

func (x *DBValue) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DBValue) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

type DBEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []*DBValue `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
}

func (x *DBEntry) Reset() {
	*x = DBEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_internal_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBEntry) ProtoMessage() {}

func (x *DBEntry) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_internal_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBEntry.ProtoReflect.Descriptor instead.
func (*DBEntry) Descriptor() ([]byte, []int) {
	return file_ubikom_internal_proto_rawDescGZIP(), []int{5}
}

func (x *DBEntry) GetValue() []*DBValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type ImapInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NextMailboxUid uint32 `protobuf:"varint,1,opt,name=nextMailboxUid,proto3" json:"nextMailboxUid,omitempty"`
	NextMessageUid uint32 `protobuf:"varint,2,opt,name=nextMessageUid,proto3" json:"nextMessageUid,omitempty"`
}

func (x *ImapInfo) Reset() {
	*x = ImapInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_internal_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImapInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImapInfo) ProtoMessage() {}

func (x *ImapInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_internal_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImapInfo.ProtoReflect.Descriptor instead.
func (*ImapInfo) Descriptor() ([]byte, []int) {
	return file_ubikom_internal_proto_rawDescGZIP(), []int{6}
}

func (x *ImapInfo) GetNextMailboxUid() uint32 {
	if x != nil {
		return x.NextMailboxUid
	}
	return 0
}

func (x *ImapInfo) GetNextMessageUid() uint32 {
	if x != nil {
		return x.NextMessageUid
	}
	return 0
}

type ImapMailbox struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name           string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Attribute      []string `protobuf:"bytes,2,rep,name=attribute,proto3" json:"attribute,omitempty"`
	Uid            uint32   `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"` // Unique ID for this mailbox. It never changes, even when mailbox is renamed.
	NextMessageUid uint32   `protobuf:"varint,4,opt,name=nextMessageUid,proto3" json:"nextMessageUid,omitempty"`
}

func (x *ImapMailbox) Reset() {
	*x = ImapMailbox{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_internal_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImapMailbox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImapMailbox) ProtoMessage() {}

func (x *ImapMailbox) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_internal_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImapMailbox.ProtoReflect.Descriptor instead.
func (*ImapMailbox) Descriptor() ([]byte, []int) {
	return file_ubikom_internal_proto_rawDescGZIP(), []int{7}
}

func (x *ImapMailbox) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImapMailbox) GetAttribute() []string {
	if x != nil {
		return x.Attribute
	}
	return nil
}

func (x *ImapMailbox) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ImapMailbox) GetNextMessageUid() uint32 {
	if x != nil {
		return x.NextMessageUid
	}
	return 0
}

type ImapMailboxes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mailbox        []*ImapMailbox `protobuf:"bytes,1,rep,name=mailbox,proto3" json:"mailbox,omitempty"`
	Subscribed     []string       `protobuf:"bytes,2,rep,name=subscribed,proto3" json:"subscribed,omitempty"`
	NextMailboxUid uint32         `protobuf:"varint,3,opt,name=nextMailboxUid,proto3" json:"nextMailboxUid,omitempty"`
}

func (x *ImapMailboxes) Reset() {
	*x = ImapMailboxes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_internal_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImapMailboxes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImapMailboxes) ProtoMessage() {}

func (x *ImapMailboxes) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_internal_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImapMailboxes.ProtoReflect.Descriptor instead.
func (*ImapMailboxes) Descriptor() ([]byte, []int) {
	return file_ubikom_internal_proto_rawDescGZIP(), []int{8}
}

func (x *ImapMailboxes) GetMailbox() []*ImapMailbox {
	if x != nil {
		return x.Mailbox
	}
	return nil
}

func (x *ImapMailboxes) GetSubscribed() []string {
	if x != nil {
		return x.Subscribed
	}
	return nil
}

func (x *ImapMailboxes) GetNextMailboxUid() uint32 {
	if x != nil {
		return x.NextMailboxUid
	}
	return 0
}

type ImapMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content           []byte   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Flag              []string `protobuf:"bytes,2,rep,name=flag,proto3" json:"flag,omitempty"`
	ReceivedTimestamp uint64   `protobuf:"varint,3,opt,name=received_timestamp,json=receivedTimestamp,proto3" json:"received_timestamp,omitempty"`
	Size              uint64   `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Uid               uint32   `protobuf:"varint,5,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *ImapMessage) Reset() {
	*x = ImapMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_internal_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImapMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImapMessage) ProtoMessage() {}

func (x *ImapMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_internal_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImapMessage.ProtoReflect.Descriptor instead.
func (*ImapMessage) Descriptor() ([]byte, []int) {
	return file_ubikom_internal_proto_rawDescGZIP(), []int{9}
}

func (x *ImapMessage) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ImapMessage) GetFlag() []string {
	if x != nil {
		return x.Flag
	}
	return nil
}

func (x *ImapMessage) GetReceivedTimestamp() uint64 {
	if x != nil {
		return x.ReceivedTimestamp
	}
	return 0
}

func (x *ImapMessage) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ImapMessage) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp uint64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EventType EventType `protobuf:"varint,3,opt,name=event_type,json=eventType,proto3,enum=Ubikom.EventType" json:"event_type,omitempty"`
	User1     string    `protobuf:"bytes,4,opt,name=user1,proto3" json:"user1,omitempty"`
	User2     string    `protobuf:"bytes,5,opt,name=user2,proto3" json:"user2,omitempty"`
	Message   string    `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Data1     string    `protobuf:"bytes,7,opt,name=data1,proto3" json:"data1,omitempty"`
	Component string    `protobuf:"bytes,8,opt,name=component,proto3" json:"component,omitempty"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_internal_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_internal_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_ubikom_internal_proto_rawDescGZIP(), []int{10}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Event) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_ET_NONE
}

func (x *Event) GetUser1() string {
	if x != nil {
		return x.User1
	}
	return ""
}

func (x *Event) GetUser2() string {
	if x != nil {
		return x.User2
	}
	return ""
}

func (x *Event) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Event) GetData1() string {
	if x != nil {
		return x.Data1
	}
	return ""
}

func (x *Event) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

type CopyMailboxesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OldKey []byte `protobuf:"bytes,1,opt,name=oldKey,proto3" json:"oldKey,omitempty"`
	NewKey []byte `protobuf:"bytes,2,opt,name=newKey,proto3" json:"newKey,omitempty"`
}

func (x *CopyMailboxesRequest) Reset() {
	*x = CopyMailboxesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_internal_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopyMailboxesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyMailboxesRequest) ProtoMessage() {}

func (x *CopyMailboxesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_internal_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyMailboxesRequest.ProtoReflect.Descriptor instead.
func (*CopyMailboxesRequest) Descriptor() ([]byte, []int) {
	return file_ubikom_internal_proto_rawDescGZIP(), []int{11}
}

func (x *CopyMailboxesRequest) GetOldKey() []byte {
	if x != nil {
		return x.OldKey
	}
	return nil
}

func (x *CopyMailboxesRequest) GetNewKey() []byte {
	if x != nil {
		return x.NewKey
	}
	return nil
}

type CopyMailboxesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CopyMailboxesResponse) Reset() {
	*x = CopyMailboxesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_internal_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopyMailboxesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyMailboxesResponse) ProtoMessage() {}

func (x *CopyMailboxesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_internal_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyMailboxesResponse.ProtoReflect.Descriptor instead.
func (*CopyMailboxesResponse) Descriptor() ([]byte, []int) {
	return file_ubikom_internal_proto_rawDescGZIP(), []int{12}
}

type CheckMailboxKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CheckMailboxKeyRequest) Reset() {
	*x = CheckMailboxKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_internal_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckMailboxKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMailboxKeyRequest) ProtoMessage() {}

func (x *CheckMailboxKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_internal_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMailboxKeyRequest.ProtoReflect.Descriptor instead.
func (*CheckMailboxKeyRequest) Descriptor() ([]byte, []int) {
	return file_ubikom_internal_proto_rawDescGZIP(), []int{13}
}

func (x *CheckMailboxKeyRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *CheckMailboxKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CheckMailboxKeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CheckMailboxKeyResponse) Reset() {
	*x = CheckMailboxKeyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ubikom_internal_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckMailboxKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMailboxKeyResponse) ProtoMessage() {}

func (x *CheckMailboxKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ubikom_internal_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMailboxKeyResponse.ProtoReflect.Descriptor instead.
func (*CheckMailboxKeyResponse) Descriptor() ([]byte, []int) {
	return file_ubikom_internal_proto_rawDescGZIP(), []int{14}
}

var File_ubikom_internal_proto protoreflect.FileDescriptor

var file_ubikom_internal_proto_rawDesc = []byte{
	0x0a, 0x15, 0x75, 0x62, 0x69, 0x6b, 0x6f, 0x6d, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x55, 0x62, 0x69, 0x6b, 0x6f, 0x6d, 0x1a,
	0x0c, 0x75, 0x62, 0x69, 0x6b, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61,
	0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcd, 0x01, 0x0a, 0x09, 0x4b, 0x65, 0x79,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x35, 0x0a, 0x16, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x15, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1a, 0x0a,
	0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x2d, 0x0a, 0x12, 0x64, 0x69, 0x73,
	0x61, 0x62, 0x6c, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x61,
	0x62, 0x6c, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x64,
	0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x42, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x09, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x22, 0xe5, 0x01, 0x0a, 0x0f, 0x45, 0x78, 0x70,
	0x6f, 0x72, 0x74, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x35,
	0x0a, 0x16, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x15,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65,
	0x64, 0x12, 0x2d, 0x0a, 0x12, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x64,
	0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x42,
	0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x4b, 0x65, 0x79,
	0x22, 0x38, 0x0a, 0x10, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x71, 0x0a, 0x13, 0x45, 0x78,
	0x70, 0x6f, 0x72, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x55, 0x62, 0x69, 0x6b, 0x6f, 0x6d,
	0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x57, 0x0a,
	0x07, 0x44, 0x42, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x2e, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x30, 0x0a, 0x07, 0x44, 0x42, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x25, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x55, 0x62, 0x69, 0x6b, 0x6f, 0x6d, 0x2e, 0x44, 0x42, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x5a, 0x0a, 0x08, 0x49, 0x6d, 0x61, 0x70,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x26, 0x0a, 0x0e, 0x6e, 0x65, 0x78, 0x74, 0x4d, 0x61, 0x69, 0x6c,
	0x62, 0x6f, 0x78, 0x55, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x6e, 0x65,
	0x78, 0x74, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x55, 0x69, 0x64, 0x12, 0x26, 0x0a, 0x0e,
	0x6e, 0x65, 0x78, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x55, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x6e, 0x65, 0x78, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x55, 0x69, 0x64, 0x22, 0x79, 0x0a, 0x0b, 0x49, 0x6d, 0x61, 0x70, 0x4d, 0x61, 0x69, 0x6c,
	0x62, 0x6f, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x61, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x6e, 0x65, 0x78, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x55, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0e, 0x6e, 0x65, 0x78, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x55, 0x69, 0x64, 0x22,
	0x86, 0x01, 0x0a, 0x0d, 0x49, 0x6d, 0x61, 0x70, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x65,
	0x73, 0x12, 0x2d, 0x0a, 0x07, 0x6d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x55, 0x62, 0x69, 0x6b, 0x6f, 0x6d, 0x2e, 0x49, 0x6d, 0x61, 0x70,
	0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x52, 0x07, 0x6d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78,
	0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x64, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x64,
	0x12, 0x26, 0x0a, 0x0e, 0x6e, 0x65, 0x78, 0x74, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x55,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x6e, 0x65, 0x78, 0x74, 0x4d, 0x61,
	0x69, 0x6c, 0x62, 0x6f, 0x78, 0x55, 0x69, 0x64, 0x22, 0x90, 0x01, 0x0a, 0x0b, 0x49, 0x6d, 0x61,
	0x70, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x12, 0x2d, 0x0a, 0x12, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x11, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0xe1, 0x01, 0x0a, 0x05,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x30, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x55, 0x62, 0x69, 0x6b, 0x6f, 0x6d,
	0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x31, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x31, 0x12, 0x14, 0x0a, 0x05, 0x75,
	0x73, 0x65, 0x72, 0x32, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72,
	0x32, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x64,
	0x61, 0x74, 0x61, 0x31, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x61, 0x74, 0x61,
	0x31, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x22,
	0x46, 0x0a, 0x14, 0x43, 0x6f, 0x70, 0x79, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x6c, 0x64, 0x4b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6f, 0x6c, 0x64, 0x4b, 0x65, 0x79, 0x12,
	0x16, 0x0a, 0x06, 0x6e, 0x65, 0x77, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x6e, 0x65, 0x77, 0x4b, 0x65, 0x79, 0x22, 0x17, 0x0a, 0x15, 0x43, 0x6f, 0x70, 0x79, 0x4d,
	0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x3e, 0x0a, 0x16, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78,
	0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x19, 0x0a, 0x17, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78,
	0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0xc6, 0x03, 0x0a, 0x09,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x54, 0x5f,
	0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x45, 0x54, 0x5f, 0x4b, 0x45, 0x59,
	0x5f, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x01, 0x12,
	0x18, 0x0a, 0x14, 0x45, 0x54, 0x5f, 0x4e, 0x41, 0x4d, 0x45, 0x5f, 0x52, 0x45, 0x47, 0x49, 0x53,
	0x54, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x02, 0x12, 0x1b, 0x0a, 0x17, 0x45, 0x54, 0x5f,
	0x41, 0x44, 0x44, 0x52, 0x45, 0x53, 0x53, 0x5f, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x52, 0x41,
	0x54, 0x49, 0x4f, 0x4e, 0x10, 0x03, 0x12, 0x17, 0x0a, 0x12, 0x45, 0x54, 0x5f, 0x50, 0x52, 0x4f,
	0x58, 0x59, 0x5f, 0x50, 0x4f, 0x50, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10, 0xe9, 0x07, 0x12,
	0x18, 0x0a, 0x13, 0x45, 0x54, 0x5f, 0x50, 0x52, 0x4f, 0x58, 0x59, 0x5f, 0x49, 0x4d, 0x41, 0x50,
	0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10, 0xcd, 0x08, 0x12, 0x18, 0x0a, 0x13, 0x45, 0x54, 0x5f,
	0x50, 0x52, 0x4f, 0x58, 0x59, 0x5f, 0x53, 0x4d, 0x54, 0x50, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e,
	0x10, 0xb1, 0x09, 0x12, 0x1f, 0x0a, 0x1a, 0x45, 0x54, 0x5f, 0x50, 0x52, 0x4f, 0x58, 0x59, 0x5f,
	0x53, 0x4d, 0x54, 0x50, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x53, 0x45, 0x4e,
	0x54, 0x10, 0xb2, 0x09, 0x12, 0x1b, 0x0a, 0x16, 0x45, 0x54, 0x5f, 0x50, 0x52, 0x4f, 0x58, 0x59,
	0x5f, 0x57, 0x45, 0x42, 0x4d, 0x41, 0x49, 0x4c, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10, 0x95,
	0x0a, 0x12, 0x22, 0x0a, 0x1d, 0x45, 0x54, 0x5f, 0x50, 0x52, 0x4f, 0x58, 0x59, 0x5f, 0x57, 0x45,
	0x42, 0x4d, 0x41, 0x49, 0x4c, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x53, 0x45,
	0x4e, 0x54, 0x10, 0x96, 0x0a, 0x12, 0x27, 0x0a, 0x22, 0x45, 0x54, 0x5f, 0x47, 0x41, 0x54, 0x45,
	0x57, 0x41, 0x59, 0x5f, 0x55, 0x42, 0x49, 0x4b, 0x4f, 0x4d, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41,
	0x47, 0x45, 0x5f, 0x52, 0x45, 0x43, 0x45, 0x49, 0x56, 0x45, 0x44, 0x10, 0xd1, 0x0f, 0x12, 0x26,
	0x0a, 0x21, 0x45, 0x54, 0x5f, 0x47, 0x41, 0x54, 0x45, 0x57, 0x41, 0x59, 0x5f, 0x45, 0x4d, 0x41,
	0x49, 0x4c, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x52, 0x45, 0x43, 0x45, 0x49,
	0x56, 0x45, 0x44, 0x10, 0xd2, 0x0f, 0x12, 0x23, 0x0a, 0x1e, 0x45, 0x54, 0x5f, 0x47, 0x41, 0x54,
	0x45, 0x57, 0x41, 0x59, 0x5f, 0x55, 0x42, 0x49, 0x4b, 0x4f, 0x4d, 0x5f, 0x4d, 0x45, 0x53, 0x53,
	0x41, 0x47, 0x45, 0x5f, 0x53, 0x45, 0x4e, 0x54, 0x10, 0xd3, 0x0f, 0x12, 0x22, 0x0a, 0x1d, 0x45,
	0x54, 0x5f, 0x47, 0x41, 0x54, 0x45, 0x57, 0x41, 0x59, 0x5f, 0x45, 0x4d, 0x41, 0x49, 0x4c, 0x5f,
	0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x53, 0x45, 0x4e, 0x54, 0x10, 0xd4, 0x0f, 0x12,
	0x13, 0x0a, 0x0e, 0x45, 0x54, 0x5f, 0x50, 0x41, 0x47, 0x45, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x45,
	0x44, 0x10, 0xb9, 0x17, 0x32, 0xb0, 0x01, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4c, 0x0a, 0x0d, 0x43, 0x6f, 0x70, 0x79, 0x4d, 0x61, 0x69,
	0x6c, 0x62, 0x6f, 0x78, 0x65, 0x73, 0x12, 0x1c, 0x2e, 0x55, 0x62, 0x69, 0x6b, 0x6f, 0x6d, 0x2e,
	0x43, 0x6f, 0x70, 0x79, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x55, 0x62, 0x69, 0x6b, 0x6f, 0x6d, 0x2e, 0x43, 0x6f,
	0x70, 0x79, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x0f, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4d, 0x61, 0x69, 0x6c,
	0x62, 0x6f, 0x78, 0x4b, 0x65, 0x79, 0x12, 0x1e, 0x2e, 0x55, 0x62, 0x69, 0x6b, 0x6f, 0x6d, 0x2e,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x4b, 0x65, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x55, 0x62, 0x69, 0x6b, 0x6f, 0x6d, 0x2e,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x4b, 0x65, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ubikom_internal_proto_rawDescOnce sync.Once
	file_ubikom_internal_proto_rawDescData = file_ubikom_internal_proto_rawDesc
)

func file_ubikom_internal_proto_rawDescGZIP() []byte {
	file_ubikom_internal_proto_rawDescOnce.Do(func() {
		file_ubikom_internal_proto_rawDescData = protoimpl.X.CompressGZIP(file_ubikom_internal_proto_rawDescData)
	})
	return file_ubikom_internal_proto_rawDescData
}

var file_ubikom_internal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ubikom_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_ubikom_internal_proto_goTypes = []interface{}{
	(EventType)(0),                  // 0: Ubikom.EventType
	(*KeyRecord)(nil),               // 1: Ubikom.KeyRecord
	(*ExportKeyRecord)(nil),         // 2: Ubikom.ExportKeyRecord
	(*ExportNameRecord)(nil),        // 3: Ubikom.ExportNameRecord
	(*ExportAddressRecord)(nil),     // 4: Ubikom.ExportAddressRecord
	(*DBValue)(nil),                 // 5: Ubikom.DBValue
	(*DBEntry)(nil),                 // 6: Ubikom.DBEntry
	(*ImapInfo)(nil),                // 7: Ubikom.ImapInfo
	(*ImapMailbox)(nil),             // 8: Ubikom.ImapMailbox
	(*ImapMailboxes)(nil),           // 9: Ubikom.ImapMailboxes
	(*ImapMessage)(nil),             // 10: Ubikom.ImapMessage
	(*Event)(nil),                   // 11: Ubikom.Event
	(*CopyMailboxesRequest)(nil),    // 12: Ubikom.CopyMailboxesRequest
	(*CopyMailboxesResponse)(nil),   // 13: Ubikom.CopyMailboxesResponse
	(*CheckMailboxKeyRequest)(nil),  // 14: Ubikom.CheckMailboxKeyRequest
	(*CheckMailboxKeyResponse)(nil), // 15: Ubikom.CheckMailboxKeyResponse
	(Protocol)(0),                   // 16: Ubikom.Protocol
	(*anypb.Any)(nil),               // 17: google.protobuf.Any
}
var file_ubikom_internal_proto_depIdxs = []int32{
	16, // 0: Ubikom.ExportAddressRecord.protocol:type_name -> Ubikom.Protocol
	17, // 1: Ubikom.DBValue.payload:type_name -> google.protobuf.Any
	5,  // 2: Ubikom.DBEntry.value:type_name -> Ubikom.DBValue
	8,  // 3: Ubikom.ImapMailboxes.mailbox:type_name -> Ubikom.ImapMailbox
	0,  // 4: Ubikom.Event.event_type:type_name -> Ubikom.EventType
	12, // 5: Ubikom.ProxyService.CopyMailboxes:input_type -> Ubikom.CopyMailboxesRequest
	14, // 6: Ubikom.ProxyService.CheckMailboxKey:input_type -> Ubikom.CheckMailboxKeyRequest
	13, // 7: Ubikom.ProxyService.CopyMailboxes:output_type -> Ubikom.CopyMailboxesResponse
	15, // 8: Ubikom.ProxyService.CheckMailboxKey:output_type -> Ubikom.CheckMailboxKeyResponse
	7,  // [7:9] is the sub-list for method output_type
	5,  // [5:7] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_ubikom_internal_proto_init() }
func file_ubikom_internal_proto_init() {
	if File_ubikom_internal_proto != nil {
		return
	}
	file_ubikom_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ubikom_internal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ubikom_internal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportKeyRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ubikom_internal_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportNameRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ubikom_internal_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportAddressRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ubikom_internal_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ubikom_internal_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ubikom_internal_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImapInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ubikom_internal_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImapMailbox); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ubikom_internal_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImapMailboxes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ubikom_internal_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImapMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ubikom_internal_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ubikom_internal_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopyMailboxesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ubikom_internal_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopyMailboxesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ubikom_internal_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckMailboxKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ubikom_internal_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckMailboxKeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ubikom_internal_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ubikom_internal_proto_goTypes,
		DependencyIndexes: file_ubikom_internal_proto_depIdxs,
		EnumInfos:         file_ubikom_internal_proto_enumTypes,
		MessageInfos:      file_ubikom_internal_proto_msgTypes,
	}.Build()
	File_ubikom_internal_proto = out.File
	file_ubikom_internal_proto_rawDesc = nil
	file_ubikom_internal_proto_goTypes = nil
	file_ubikom_internal_proto_depIdxs = nil
}
